on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Get StaticCheck
      run: go get honnef.co/go/tools/cmd/staticcheck
    - name: Checkout code
      uses: actions/checkout@v2
    - id: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod              # Module download cache
          ~/.cache/go-build         # Build cache (Linux)
          ~/Library/Caches/go-build # Build cache (Mac)
          '%LocalAppData%\go-build' # Build cache (Windows)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get Dependencies
      run: go mod download
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Vet
      run: go vet ./...
    - name: StaticCheck
      run: staticcheck ./...
    - name: Test
      run: go test ./...
    - name: Test with race detector
      run: go test -race ./...

